#version: '3.1'

#사설망 네트워크 생성
networks:
  kosa_network:
    driver: bridge

#서비스 선언
services:
  #was1과 was2 생성
  was1:
    image: seungju0104/hello-web:latest
    networks:
      - kosa_network
  
  was2:
    image: seungju0104/hello-web
    networks:
      - kosa_network

#nginx 생성
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ~/nginx/nginx.conf:/etc/neginx/nginx.conf
    networks:
      - kosa_network
    depends_on:
      - was1
      - was2
