name: Our Workflow
on: 
  push: # 동작시 어떤 것을 가지고 동작할 것인가
    branches: [main]
jobs: #단계별 실행할 작업들
  checkout:
    runs-on: ubuntu-latest #runs-on은 가상 머신 운영체제 의미. 여기서는 우분투 최신버전
    steps:
      - uses: actions/checkout@v3 #uses는 GitHub Action에서 사용할 명령어
      
      - name: Set up JDK17
        uses: actions/setup-java@v3 #GitHub Action에서 설치 제공
        with:
          java-vesrion: '17'
          distrubution: 'temurin' #배포도 있어야한다.

      - name: build grant Authorization
        run: chmod +x gradlew
          
      - name: build gradlew
        run: ./gradlew bootJar
        

      - name: docker hub login
        uses: docker/login-action@v1 #docker 로그인은 GitHub Action에서 제공
        with:
          username: ${{secrets.USERNAME}} # ${{secrets.???}}으로 외부에 보이지 않게 보안처리 가능
          password: ${{secrets.PASSWORD}} # ${{secrets.???}}으로 외부에 보이지 않게 보안처리 가능
          
      - name: docker image build
        run: docker build -t seungju0104/hello-web:latest

      - name: docker hub push
        run: docker push seungju0104/hello-web:latest

      

      
# GitHub에서 작성해 저장하면 자동으로 Commit과 Push가 수행된다.
