name: Our Workflow
on: push # 동작시 어떤 것을 가지고 동작할 것인가
jobs: #단계별 실행할 작업들
  checkout:
    runs-on: ubuntu-latest #runs-on은 가상 머신 운영체제 의미. 여기서는 우분투 최신버전
    steps:
      - run: ls -al #run은 Shell에서 사용할 명령어
      - uses: actions/checkout@v3 #uses는 GitHub Action에서 사용할 명령어
      - run: ls -al
# GitHub에서 작성해 저장하면 자동으로 Commit과 Push가 수행된다.
